CREATE TABLE Users (
    id INT IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(50) NOT NULL UNIQUE,
    password NVARCHAR(255) NOT NULL,
    role NVARCHAR(20) NOT NULL
);

CREATE TABLE Visitors (
    id INT IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(100) NOT NULL,
    cpf NVARCHAR(14) NOT NULL,
    phone NVARCHAR(20) NOT NULL,
    sector NVARCHAR(100) NOT NULL,
    created_at DATETIME DEFAULT GETDATE()
);
